### ISSUE TITLE
Issue with latest release of Numpy

### ISSUE THREAD

**Issue by standage** [HadrienG/InSilicoSeq#101]
It looks like the latest version of numpy, [1.16.3](https://github.com/numpy/numpy/releases/tag/v1.16.3), added a new default to `numpy.load` which leads to runtime errors with InSilicoSeq. Looks like `allow_pickle=True` needs to be added to [this line](https://github.com/HadrienG/InSilicoSeq/blob/acfe39845268cc9ad7d0c7b42eea0dc69f910fbf/iss/error_models/__init__.py#L39) and possibly others.

**Comment by standage** [comment]
Related: https://github.com/bioconda/bioconda-recipes/pull/15240

**Comment by HadrienG** [comment]
Thanks for the bug report! it should be fixed in `1.3.6`
