### ISSUE TITLE
problem with --draft option

### ISSUE THREAD

**Issue by MapleHe** [HadrienG/InSilicoSeq#113]
Thank you for your development !

I encountered an error `Fasta record not found in abundance file:` while using --draft option with multiple FASTA inputs. 

The error was raised in `app.py` line 193.

https://github.com/HadrienG/InSilicoSeq/blob/1a2e6d6812387643e4596fc22f581b7457506d79/iss/app.py#L178-L195

I traced back to `abundance.py` and found that the "key" was lost in `abundance.py` because the `draft_dic` dictionary was reinitialized at the start of each loop. 

https://github.com/HadrienG/InSilicoSeq/blob/1a2e6d6812387643e4596fc22f581b7457506d79/iss/abundance.py#L216-L237

I thought the `draft_dic` should be initialized before the for-loop.

**Comment by HadrienG** [comment]
Hi!

Thanks for reporting this and sorry for the slow response. I'll be able to take a look next week.

**Comment by MapleHe** [comment]
It's ok ~ Thank you for your response.

**Comment by HadrienG** [comment]
Should be fixed in `1.4.3`!
