### ISSUE TITLE
InSilicoSeq: error: unrecognized arguments: -–n_reads 0.5M

### ISSUE THREAD

**Issue by novitch** [HadrienG/InSilicoSeq#118]
Hi, 
I would like to try yorsoft but i am unable to use the n_reads option.

The soft works well if I do not choose the n_reads but i'd like to increase the simulation depth

Thanks,
Alban,

**Comment by novitch** [comment]
Here is my command line:
````

iss generate -–n_reads 5000 -–seed 8283416 --cpus 1 --draft ../genomes_db/GCF_001405535.1_13414_6_71_genomic.fna ../genomes_db/GCF_002222615.2_ASM222261v2_genomic.fna  --model hiseq --output simulation
````
which produces:
usage: iss [subcommand] [options]
InSilicoSeq: error: unrecognized arguments: –n_reads 5000 -–seed 8283416


With iss version 1.4.3

**Comment by novitch** [comment]
also it does not recognize --seed

**Comment by novitch** [comment]
sorry bad use of -- symbols

One hundred times sorry

**Comment by HadrienG** [comment]
No worries, glad you got it to work.
