### ISSUE TITLE
The new version does not run

### ISSUE THREAD

**Issue by cuencam** [HadrienG/InSilicoSeq#128]
In line 242 from the app.py script, you are deleting the current record, but this happens while is being used, causing the program to fail.

**Comment by HadrienG** [comment]
Hi!

I've been using version `1.4.4`(the latest) and it has not crashed on me yet. Could you share with me:

* the exact command you are using
* the error message you're getting
* the operating system you're using
* some info about your input dataset (i.e. biggest record, number of genomes)

so I can investigate this?

Thanks,
Hadrien

**Comment by HadrienG** [comment]
I've investigated this a bit more, and it turns out deleting nested variables is python >= 3.2 specific.
Installing InSilicoSeq with a recent version of python3 will solve this issue.

**Comment by cuencam** [comment]
I think this solves the issue. I have it running now.

Thanks!
Miguel
