### ISSUE TITLE
installation succeed, but iss generate failed

### ISSUE THREAD

**Issue by xiaole99** [HadrienG/InSilicoSeq#142]
Hi,

Nice tool.

I try to install by both pip and miniconda. Both make it. However, when I run
>iss generate --genomes SRS121011.fasta --model miseq --output miseq_reads

It reported:
>Traceback (most recent call last):
>File "/home/yinxiaole/.local/bin/iss", line 7, in <module>
>   from iss.app import main
>SyntaxError: can not delete variable 'record' referenced in nested scope

Where is wrong with my code?
Thanks.

**Comment by HadrienG** [comment]
Hi! 

There is nothing wrong with your command, only that the latest version of `InSilicoSeq` breaks python2 compatibility.

Reinstalling using a python3 conda environment should solve your issue.

Best,
Hadrien.

**Comment by xiaole99** [comment]
Thanks for your prompt reply.  I will try python3.
