### ISSUE TITLE
Can read length be specified?

### ISSUE THREAD

**Issue by vr1087** [HadrienG/InSilicoSeq#145]
Is there a way to specify a read length or can only 35 bp long reads be generated? I did not see any option for this listed. I am using a custom model generated from a dataset with 151 bp reads.

I installed via pip: iss version 1.4.5

**Comment by HadrienG** [comment]
Hi! 

There is currently no way to specify a custom read with `iss generate`. 
If you are using a custom model, why not building the model with reads that are 35bp long?

Best,
Hadrien

**Comment by vr1087** [comment]
Sorry, I am actually wondering if the user can change the length of the simulated reads. Thank you.

**Comment by HadrienG** [comment]
You can't, the read length is fixed in the error model.

**Comment by vr1087** [comment]
Got it. If using a custom model, will the read length always be 35 bp? Even if I built the model with reads of a different length? That is the behavior I observed. Thanks for your response.

**Comment by HadrienG** [comment]
The read length should be the length of the shortest read from the run you used a input for `iss model`. It should be changed for the mode in a future release, but for now you may want to discard any abnormally short reads from your input dataset.

Hope that helps,
/Hadrien

**Comment by vr1087** [comment]
Helps plenty. Thank you!
