### ISSUE TITLE
Insert Size Distributions of built-in Error models

### ISSUE THREAD

**Issue by your-highness** [HadrienG/InSilicoSeq#150]
For anyone interested here are read lengths and insert size distributions of the built-in models:

-	MiSeq
Readlength: 301bp
Insert Size Distribution:
 ![miseq](https://user-images.githubusercontent.com/1949888/75985073-e3c6bf00-5eeb-11ea-8dbd-3f18d9ace011.png)

-	HiSeq
Readlength: 126bp
Insert Size Distribution:
 ![hiseq](https://user-images.githubusercontent.com/1949888/75985070-e2959200-5eeb-11ea-9faf-024f942d0ea4.png)

-	NovaSeq
Readlength: 151bp
Insert Size Distribution:
 ![novaseq](https://user-images.githubusercontent.com/1949888/75985075-e3c6bf00-5eeb-11ea-9b72-13f063f17aaa.png)

Please note that InSilicoSeq’s definition of the insert size differs from SAMv1 TLEN defintion. The given insert size reflects the distance between 3’-ends of reads. Resulting TLEN is `(2 * read_length + insert_size)`, _i.e._ MiSeq Error model fragment lengths are between 600 and 1600bp.

**Comment by HadrienG** [comment]
Thanks! I'll try to incorporate that info in the documentation in a future release.
The template length definition is a pet peeve of mine 🤭 I've always thought the distance between mapped fragments should be called insert size, and template length should be the total length of the biological sequence, sorry if it caused confusion!

Please also note that if one of your input genome is shorter than the maximum insert size of a model, there is a chance to get negative insert size (your reads may overlap)

/Hadrien

**Comment by your-highness** [comment]
Thanks for your answer @HadrienG !

I know that there's an ongoing debate how the cDNA physical fragment length relates to template length ([SAMv1 TLEN](https://samtools.github.io/hts-specs/SAMv1.pdf)) and insert size are. The term "insert size" is ill-defined which could refer to either the inserted DNA between sequencing adapters (_i.e._ fragment size) or the length of sequence between 3' ends of mapped reads (_i.e._ highly dependent on sequenced read length and operations like read trimming). IMHO to avoid any confusion it's best to always refer to the TLEN/fragment size convention
see also https://www.biostars.org/p/106126/ 

Johannes
