### ISSUE TITLE
Using information from csv files

### ISSUE THREAD

**Issue by Tj-Idowu** [HadrienG/InSilicoSeq#151]
I have a large number of fastq files that I am using, over 100 files, and it would take a long time to type all of them out as well as the number of reads for each fastq. Is there a way to input a text or csv file with the information and allow InSilicoSeq to run on it? Thank you

**Comment by HadrienG** [comment]
I'm not sure I understand your question, as InSilicoSeq does not take fastq files in input.
Can you give me the command that you'd like to execute and maybe a `ls` of your input directory?

/Hadrienn
