### ISSUE TITLE
How to fix read length ?

### ISSUE THREAD

**Issue by lmanchon** [HadrienG/InSilicoSeq#155]
--Hi,

i have used the command: 
'iss generate --cpus 8 -n 80M --genomes chr8.fasta --model novaseq -z --output novaseq_reads'

this command generate paired-end reads 150bp length.
How to set paired-end with 50bp length ?

Thank you --

**Comment by HadrienG** [comment]
Hi,

You can't specify a custom read length with `iss generate`. If you want NovaSeq 2x50bp you'de have to train a model with an existing 2*50bp dataset with `iss model` first.

If you have a good public dataset in mind I'm happy to build the model and include it in the next InSilicoSeq release.

Best,
Hadrien
