### ISSUE TITLE
path to saving file

### ISSUE THREAD

**Issue by gregoruar** [HadrienG/InSilicoSeq#164]
Hi, Hadrien! I hope your thesis is doing well:)
I would like to propose a minor change to --output flag. According to the doc, it takes only the prefix for the saved generated reads. For me it will be very useful if you add the possibility of providing the path to the saving folder: '/path/to/folder/read_prefix'.

**Comment by HadrienG** [comment]
Hi!

You can already do that.
Sorry if it's unclear from the documentation, I'll try to clarify or add an example for next release.

Best,
/Hadrien
