### ISSUE TITLE
coverage option

### ISSUE THREAD

**Issue by gregoruar** [HadrienG/InSilicoSeq#165]
Another question I had was about the coverage option. In particular, I was interested, how does iss identifies genome based on the name I provide in the coverage file. Does it simply check if the name is in the identifier (going after '>' in fasta file)? Or there is something more difficult, like regexp in place?

**Comment by HadrienG** [comment]
Hi!

The names in the coverage file need to be the exact identifiers present in the input fasta files up until the first space.

Example fasta header:
```
>NZ_CP015936.1 Legionella pneumophila strain C5_P chromosome, complete genome
```

Then the coverage file:

```
NZ_CP015936.1   30
```

The abundance files work the same way.

Hope that helps,
Hadrien.
