### ISSUE TITLE
Multi-fasta subset simulation

### ISSUE THREAD

**Issue by ShaBioinformer** [HadrienG/InSilicoSeq#183]
Hi Hadrien,
I have a problem in simulating a subset of genomes present in multi-fasta using **iss version 1.5.1**
Imagine the multi-fasta file contains three genomes A,B,C.
If the abundance file contains **A and B** and their abundances, simulation fails with both of these commands;
`iss generate --genomes multi.fasta --model miseq --output test --n_reads 1K --abundance_file AB.tsv`
`iss generate --genomes multi.fasta --model miseq --output test --n_reads 1K --abundance_file AB.tsv --n_genomes 2`

`ERROR:iss.app:Fasta record not found in abundance file: 'NC_022663.1'`**(which is Genome C)**

**Comment by HadrienG** [comment]
Hi,

Sorry for the delay, this isseu fell through the cracks apparently. Iäll take a look and come back to you.

/Hadrien

**Comment by ShaBioinformer** [comment]
Hi, Thanks!

**Comment by HadrienG** [comment]
Hi!

I took some time to look at your issue, and I'm not really satisfied with any implementation of allowing incomplete abundance files at this time.

If you want to use abundance files, I would remove the unwanted genomes from your multi-fasta at this time.
I will be closing this issue for now, but I don't rule out implementing this in the future.


Best,
Hadrien.
