### ISSUE TITLE
Unexpected distribution of insert sizes from paired-end HiSeq simulation

### ISSUE THREAD

**Issue by allind** [HadrienG/InSilicoSeq#186]
I am simulating paired-end HiSeq reads from a single genome, and the insert sizes of the simulated reads are very different from what is expected from a HiSeq run. The insert sizes of the resulting reads seem to be evenly distributed between ~300-1200 bp (see here: [simulated_insert_metric.pdf](https://github.com/HadrienG/InSilicoSeq/files/5104680/ISS_simulated_insert_metric.pdf)). Real sequencing data from HiSeq runs has insert sizes that peak around an expected value. I'm not sure what would be causing this.

**Comment by jsgounot** [comment]
Do we have an update on this? I know the repo is quite old and maybe no one is managing it anymore, but a random insert size is not representative of a true dataset and can be a big issue for some softwares.

**Comment by HadrienG** [comment]
Fixed in 2.0.0
