### ISSUE TITLE
coverage_file documentation

### ISSUE THREAD

**Issue by TMiguelT** [HadrienG/InSilicoSeq#191]
Hi, I'm just a trying to understand the `--coverage_file` parameter. I suppose that it sets the parameters of the distribution defined by `--coverage`, but I don't understand the format of the file. I suppose each line will relate to one genome?

In addition, I'm interested if InSilicoSeq can handle something like a BED file of regions so that I can customize the coverage on a per-region basis within one single genome.

**Comment by cilliannolan** [comment]
I am also interested in using InSilicoSeq to simulate genomes with coverage dependent on the region, and would like to know more about the `--coverage_file` parameter.

**Comment by TMiguelT** [comment]
I've had a dig into the source code, which says:

https://github.com/HadrienG/InSilicoSeq/blob/52ad1fbbb6f454b41d1d54bed0c9b9ece556319f/iss/abundance.py#L16-L19

So if you have only one genome, you will have a file such as:
```
some_genome    50
```

**Comment by HadrienG** [comment]
Hi folks!

using a bed file is a good idea, but I don't have much time to add new functionality at the moment. I'll definitely put it on the wishlist though!

Concerning the `--coverage_file` option, I tried to clarify how it works in the documantation.


Best,
Hadrien

**Comment by TMiguelT** [comment]
Thanks for documenting this! Since the issue was about documentation I'll close it now. Unfortunately I don't think I have time to add the per-region coverage feature either, but it certainly would be nice at some point.
