### ISSUE TITLE
ERROR:iss.app:Failed to open genome(s) file:[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by slvrshot** [HadrienG/InSilicoSeq#198]
Hello I've used your tool before to simulate sequencing reads but recently I keep coming across these strange errors. I am in the directory of the file and I run this: 

```
user@user$ ls
GK124.fasta      M1.fasta  G7944.fasta   LT592161_WHO_Y.fasta  test X.fasta

user@user$ iss generate --genomes LT592161_WHO_Y.fasta --model miseq --output miseq_reads
INFO:iss.app:Starting iss generate
INFO:iss.app:Using kde ErrorModel
INFO:iss.util:Stitching input files together
ERROR:iss.app:Failed to open genome(s) file:[Errno 2] No such file or directory: 'LT592161_WHO_Y.fasta'

```
I tested the example file and it works just fine. My other assemblies in this directory don't work at all. Like I said I've ran this on hundreds of isolates just fine but recently it seems it will only work on the test assembly. I've checked write and read permissions and those look good. Please help!

**Comment by HadrienG** [comment]
Hi!

Thanks for reporting this. Unfortunately I'm not able to reproduce the bug on my machines.
Could you:

- run `iss generate` with the `--debug` flag and attach the log to this issue?
- tell me more about the permissions in your folder (per example from the `stat` command)
- eventually send me one of the offending files if they are not sensitive data (along with info about permissions and ownership)

Best,
Hadrien

**Comment by slvrshot** [comment]
This was an issue with our HPC...fixed.
