### ISSUE TITLE
Seems like the error free profile performs worse than the error profile

### ISSUE THREAD

**Issue by Kumereng** [HadrienG/InSilicoSeq#200]
When simulating from bacterial genomes, it appears that when no error profile is used (--model basic), it performs worse after classification on kraken2 than when a Miseq profile is used for instance.

**Comment by HadrienG** [comment]
`--model basic` is not an error-free error model. All bases have Q30 and all nucleotides have equal substitution rate. For error-free reads, you can use `--model perfect`.
