### ISSUE TITLE
UserWarning: semaphore_tracker Error

### ISSUE THREAD

**Issue by Tj-Idowu** [HadrienG/InSilicoSeq#201]
Hello, I am trying to use iss to create fastq files from a list of microbes with the corresponding read count. I am coming across the error message below and I don't know how to fix it. Can you please help me figure it out? I am getting output files for some of the microbe genomes but not all of them. Thank you.

>  iss generate --genomes GCF_001484935.1_ASM148493v1_genomic.fna --n_reads 4381122 --model miseq     --output ww_Acinetobacter_johnsoniiESC[K
ESC[K
Command exit status:ESC[K
  143ESC[K
ESC[K
Command output:ESC[K
  total 5ESC[K
  drwxr-xr-x  2 12355656 shared    2 Feb 22 19:40 .ESC[K
  drwxr-xr-x 22 12355656 shared   20 Feb 22 19:37 ..ESC[K
  -rw-r--r--  1 12355656 shared    0 Feb 22 19:40 .command.beginESC[K
  -rw-r--r--  1 12355656 shared    0 Feb 22 19:40 .command.errESC[K
  -rw-r--r--  1 12355656 shared    0 Feb 22 19:40 .command.logESC[K
  -rw-r--r--  1 12355656 shared    0 Feb 22 19:40 .command.outESC[K
  -rw-r--r--  1 12355656 shared 2986 Feb 22 19:37 .command.runESC[K
  -rw-r--r--  1 12355656 shared  201 Feb 22 19:37 .command.shESC[K
  lrwxrwxrwx  1 12355656 shared   80 Feb 22 19:40 GCF_001484935.1_ASM148493v1_genomic.fna -> /path/tome/bacterial-ncbi-genomes/GCF_001484935.1_ASM148493v1_genomic.fnaESC[K
  GCF_001484935.1_ASM148493v1_genomic.fnaESC[K
ESC[K
Command error:ESC[K
  INFO:iss.app:Starting iss generateESC[K
  INFO:iss.app:Using kde ErrorModelESC[K
  INFO:iss.util:Stitching input files togetherESC[K
  INFO:iss.app:Using lognormal abundance distributionESC[K
  INFO:iss.app:Using 2 cpus for read generationESC[K
  INFO:iss.app:Generating 4381122 readsESC[K
  INFO:iss.app:Generating reads for record: NZ_CP010350.1ESC[K
  INFO:iss.app:Generating reads for record: NZ_CP010352.1ESC[K
  /home/people/12355656/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:198: UserWarning: semaphore_tracker: There appear to be 8 leaked semaphores to clean up at shutdownESC[K

**Comment by HadrienG** [comment]
Hi!

I've never ever seen this and it's quite puzzling 😕 . Are you working in a container by any chance?


Your output seems like you're running nextflow. Could it be that somehow the warning changes the exit code of InSilicoSeq and so nextflow interrupts all the running processes?

I'd first hope that it's indeed only a warning and try to silence it, either with:

```bash
export PYTHONWARNINGS='ignore:semaphore_tracker:UserWarning'
```

before invoking `iss`, or by catching the `143` exit status with a trap: https://github.com/nextflow-io/nextflow/issues/1564

Let me know how it goes!
/Hadrien
