### ISSUE TITLE
iss util fails to remove tmp files when using multiple genomes if chromosomes have the same names

### ISSUE THREAD

**Issue by sylvainschmitt** [HadrienG/InSilicoSeq#205]
Hi,

Thank you for the nice tool. I'm running the version 1.5.2 using your [docker image](docker://hadrieng/insilicoseq:latest) in a snakemake and singularity workflow. Everything works great until I used two genomes with the option `--genomes`. As soon as I use more than one genome, iss util fails to remove the temporary file corresponding to the R1 reads:

> INFO:iss.util:Cleaning up

> ERROR:iss.util:Could not read temporary file: results/test/read.iss.tmp.Qrob_Chr01.0_R1.fastq

> ERROR:iss.util:You may have to remove temporary files manually

This is only a temporary file issue, but it stop my snakemake workflow which is problematic. A simple fix is to merge the two genomes manually before using `insilicoseq`. Nevertheless, I thought I report the bug in case it was not fixed in the last version. It may be related to #143 .

Best,

Sylvain

**Comment by sylvainschmitt** [comment]
Hello again,

Sorry but I got the origin of the error. When you are using multiple genomes `iss util` fails to clean files if the names of the chromosomes are the same in the two genomes, which is logical. But maybe an earlier test could catch this error.

Thanks again for the nice tool.

**Comment by HadrienG** [comment]
Hi,

Thanks for reportng this and for finding the root cause of the problem!
I'll try to address this in the next release.

Best,
Hadrien.
