### ISSUE TITLE
Biopython 1.79 issue

### ISSUE THREAD

**Issue by dturaev** [HadrienG/InSilicoSeq#207]
The `iss generate` command doesn't work with Biopython 1.79. It shows warnings like `"Biopython Deprecation Warning: myseq.tomutable() is deprecated; please use MutableSeq(myseq) instead."`, and leads to an exception in the joblib call. Downgrading to Biopython 1.78 fixes the issue.

**Comment by HadrienG** [comment]
I updated the bioconda recipe to require biopython <= 1.78. A minor version to fix the pip installs will follow soon
