### ISSUE TITLE
Using abundance file with drafts/plasmids

### ISSUE THREAD

**Issue by jlubin24** [HadrienG/InSilicoSeq#221]
Hello 
I ran iss with a set of genomes some of which have some contigs (<6) and/or plasmids associated with them. I setup my abundance file to id each contig separately and assigned them the same abundance.  Will this give me an accurate profile of the genomic contribution of these contigs? I realize that will make the total abundance >1, but I didn't get an error when I attempted it. 
Thanks

**Comment by jackchen129** [comment]
Have you figured out how to do this? I also have some draft genomes with multiple contigs but don't know how to include them in the abundance file. Thanks.

> Hello I ran iss with a set of genomes some of which have some contigs (<6) and/or plasmids associated with them. I setup my abundance file to id each contig separately and assigned them the same abundance. Will this give me an accurate profile of the genomic contribution of these contigs? I realize that will make the total abundance >1, but I didn't get an error when I attempted it. Thanks

Have you figured out how to do this? I also have some draft genomes with multiple contigs but don't know how to include them in the abundance file. Thanks.

**Comment by HadrienG** [comment]
Hi!

you can do this with the `--draft` and `--abundance_file` (or `--coverage_file`) options.
The entries in the abundance/coverage files should be the name of the fasta files passed to `--draft`
