### ISSUE TITLE
Simulate targeted amplicon sequecing with MiSeq

### ISSUE THREAD

**Issue by G-Molano-LA** [HadrienG/InSilicoSeq#224]
Hi!

I have read the [previous question](https://github.com/HadrienG/InSilicoSeq/issues/95) regarding the enhancement of InSilicoSeqs for simulating reads for targeted amplicon sequencing. Is this feature already implemented?

Thanks so much,

Alejandra

**Comment by mariaelf97** [comment]
That's my question as well

**Comment by HadrienG** [comment]
Hi,

It is as of `2.0.0`! You can now set `--sequence_type amplicon` and use the parameter `--readcount_file` to specify how many reads you want per amplicon.
