### ISSUE TITLE
Consider switching to pytest

### ISSUE THREAD

**Issue by mdb571** [HadrienG/InSilicoSeq#228]
Hello,

We have a bug report [#1018377](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018377) affecting insilicoseq package. Since [nose](https://github.com/nose-devs/nose/commit/0f40fa995384afad) is deprecated , Debian is gradually moving to remove support for nose. So I have made a [patch](https://salsa.debian.org/med-team/insilicoseq/-/blob/master/debian/patches/port-to-pytest.patch) that ports the current tests to run with pytest. Just wanted to give you heads up so that you can work on this. :)

**Comment by HadrienG** [comment]
Hi!

InSilicoSeq is switching to pytest in 1.6.0 (planned to release later this week)
