### ISSUE TITLE
'Seq' object has no attribute 'tomutable'

### ISSUE THREAD

**Issue by Sanrrone** [HadrienG/InSilicoSeq#232]
Dears,
I'm trying to generate reads from an multifasta (60G), I don't know if the size of the genomes trigger the error but the software doesn't ends. (Installation via conda).
`iss generate --cpus 16 --n_reads 5000000 --seed 1 --model NovaSeq --output test_1.fastq --draft humgut.fna --debug --compress`
```
DEBUG:iss.app:iss version 1.5.3
DEBUG:iss.app:Using verbose logger
INFO:iss.app:Starting iss generate
INFO:iss.app:Using kde ErrorModel
INFO:iss.app:Setting random seed to 1
DEBUG:iss.error_models.kde.KDErrorModel:Loaded ErrorProfile: /scratch/project_2007362/software/mambaforge/lib/python3.10/site-packages/iss/profiles/NovaSeq
INFO:iss.util:Stitching input files together
INFO:iss.app:Using lognormal abundance distribution
INFO:iss.app:Using 16 cpus for read generation
INFO:iss.app:Generating 5000000 reads
INFO:iss.app:Generating reads for record: HumGut_17012_1
DEBUG:iss.app:'Seq' object has no attribute 'tomutable'
```
what can I do?
regards

**Comment by nvaulin** [comment]
There is no `tomutable` function in `biopython.Seq` for now, so the iss is crashing. To make it work use a separate environment with the older biopython version installed (for instance, `biopython==1.80`)

**Comment by Sanrrone** [comment]
it works now, thank you
