### ISSUE TITLE
Bug: local variable 'n_reads' referenced before assignment when running with "coverage"

### ISSUE THREAD

**Issue by ghoresh11** [HadrienG/InSilicoSeq#253]
Hello,

Thank you for this tool and for the updated version, the performance seems to have really improved and it will come in handy for my work!

I am trying to simulate a metagenome with the "coverage" option rather than abundance (i.e. I would like to consider the genome-length in the final output), and I would like iss to generate the log-normal coverage distribution for me.

I tried running as follows:

```bash
iss generate --draft *fasta --model hiseq --coverage lognormal --n_reads 1M
```

And I get the following error:
```
Traceback (most recent call last):
  File "/home/ghoresh/.cache/pypoetry/virtualenvs/simulate-metagenome-oP5jUgnD-py3.9/bin/iss", line 8, in <module>
    sys.exit(main())
  File "/home/ghoresh/.cache/pypoetry/virtualenvs/simulate-metagenome-oP5jUgnD-py3.9/lib/python3.9/site-packages/iss/app.py", line 454, in main
    args.func(args)
  File "/home/ghoresh/.cache/pypoetry/virtualenvs/simulate-metagenome-oP5jUgnD-py3.9/lib/python3.9/site-packages/iss/app.py", line 81, in generate_reads
    n_read_pairs = n_reads // 2
UnboundLocalError: local variable 'n_reads' referenced before assignment
```

Your assistance would be appreciated!
Many thanks
Gal

**Comment by HadrienG** [comment]
Hi! Thanks for reporting this. Using `--coverage` is supposed to disable the `--n_reads` option. I'll fix and push a bugfix release asap.

**Comment by HadrienG** [comment]
Should be fixed in 2.0.1, now available with `pip`. Should be in conda shortly.

**Comment by ghoresh11** [comment]
Thank you for fixing this so quickly.

I am still though unsure about how the coverage option works when using `--num_reads`. I end up getting a file with the coverage per contig, however, the total number of reads that is generated in the FASTQ files does not match the `--num_reads` argument.

Is the coverage option meant to work with predefining number of reads? Should the values in the `coverage` file reflect the `--num_reads` argument? I seem to always get ~300,000 reads.

**Comment by ghoresh11** [comment]
I should point out that when I used the `--coverage_file` option I do get the correct number of reads, so this is only an issue when `iss` generates the coverage file using the `--coverage` option

**Comment by ghoresh11** [comment]
Please ignore my previous comments, I found where the issue was coming from in my code. Thanks again for fixing this so quickly!! 🙂
