### ISSUE TITLE
WARNING:iss.generator:--coverage_file disables --n_reads

### ISSUE THREAD

**Issue by sahilrishav2** [HadrienG/InSilicoSeq#263]
Hello,

I am trying to simulate the reads using `iss generate --draft *.fna --model novaseq --output synthetic_reads_10X --cpus 20 --coverage_file coverage_ten_strains.txt --n_reads 4M` but it gave this error:
```
INFO:iss.app:Starting iss generate
INFO:iss.generator:Using kde ErrorModel
INFO:iss.util:Stitching input files together
WARNING:iss.generator:--coverage_file is an experimental feature
WARNING:iss.generator:--coverage_file disables --n_reads
INFO:iss.generator:Using coverage file:coverage_ten_strains.txt
INFO:iss.app:Using 20 cpus for read generation
INFO:iss.app:Generating 4000000 reads
INFO:iss.util:Stitching input files together
Traceback (most recent call last):
  File "/home/rishav//.local/bin/iss", line 8, in <module>
    sys.exit(main())
  File "/home/rishav/.local/lib/python3.10/site-packages/iss/app.py", line 454, in main
    args.func(args)
  File "/home/rishav/.local/lib/python3.10/site-packages/iss/app.py", line 126, in generate_reads
    util.concatenate(temp_R1, args.output + "_R1.fastq")
  File "/home/rishav/.local/lib/python3.10/site-packages/iss/util.py", line 233, in concatenate
    with open(file_name, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'synthetic_reads_10X.iss.tmp.18_R1.fastq'
```
but when i ran this command `iss generate --draft *.fna --model novaseq --output synthetic_reads_10X --cpus 20 --coverage_file coverage_ten_strains.txt` it ran successfully. So, i think the problem is with the `--n_reads` parameter, i am unable to set it with `coverage_file` parameter options.

Could you please help me with this concern

**Comment by HadrienG** [comment]
Hi!

Thanks for reporting this. Insilicoseq is not supposed to crash in this way, as you should not be able to specify `--n_reads` and `--coverage_file` simultaneously. The number of reads will be calculated from the required coverage.

**Comment by sahilrishav2** [comment]
Than you for your response. I want to know if number of reads could be
calculated by sequencing coverage then how can we calculate sequencing
depth.

**Comment by HadrienG** [comment]
Could you clarify what you mean by coverage versus depth? Those terms are often used ambiguously/interchangeably 😊

**Comment by sahilrishav2** [comment]
Kindly go through this link:

https://bioinfo.cd-genomics.com/sequencing-depth-coverage-read-types.html

**Comment by sahilrishav2** [comment]
@HadrienG , thank you for your time and response. Now, I get it.
