### ISSUE TITLE
Simple Error Model

### ISSUE THREAD

**Issue by HadrienG** [HadrienG/InSilicoSeq#5]
Issue to track the progress on the [Roadmap](https://github.com/HadrienG/InSilicoSeq/issues/1) item "Add a simple error model"

I guess that the simplest would be to:

- [x] Add 2 parameters: mean_quality and std_dev*
- [x] Generate random quality scores following a normal distribution
- [x] Eventually modify the nucleotides whose quality aren't perfect (it never is)
- [x] write docstrings and tests

A few unknowns:
- Should the length of the sequences vary?
- To which base switch if we get an erroneous call. A random other nucleotide? I would guess a random nucl. is good enough for a simple error model.

\* I haven't added a standard deviation parameter. it is hardcoded to 0.01 but can be discussed

**Comment by Ackia** [comment]
A few unknowns:

**Should the length of the sequences vary?**

_Yes, they should vary. At least to a certain degree. Within all sequencing technologies they are varying and are often not normally distributed._

**To which base switch if we get an erroneous call. A random other nucleotide? I would guess a random nucl. is good enough for a simple error model.**

_Random should be good enough. Possibly also include INDEL?_

**Comment by HadrienG** [comment]
@Ackia the last HiSeq reads I received are all 76bp. Also, in the BEAR article, they state that "Illumina reads are generally uniform in length, reads from other technologies can vary greatly in length" which makes sense since X cycles should give you X base pairs.

Indels occur at a really low rate in Illumina data: 2.8 x 10^−6 (errors per base) for R1 insertions and 5.1 x 10^−6 (errors per base) for R1 deletions according to doi.org/10.1186/s12859-016-0976-y
I'm gonna leave them out of the simple error model, which is just really a test for me to create reads than a model we're gonna use

**Comment by Ackia** [comment]
I agree. I was mixing Illumina up with IonTorrent. My bad. Good progress!

**Comment by HadrienG** [comment]
Closed with 031454b ! 🚀
