### ISSUE TITLE
-draft option abundance file

### ISSUE THREAD

**Issue by BeckyGenomics** [HadrienG/InSilicoSeq#83]
Hello, firstly I would like to thank you for creating InsilicoSeq!

Secondly, I am using multi-config draft genomes to generate a simulated metagenome.

I was wondering if there is any option to use an abundance file with draft genomes? Just as there is with the -genomes flag? Does it also default to lognormal abundance if not specified?

Many thanks,
Becky

**Comment by bioinfoMMS** [comment]
Hi Hadrien,
Thank you for this great tool! I also would like to be able to specify abundances for draft genomes. As a user, I would be fine mixing genome IDs/names with file names (as long as it was clear in the documentation that this is what one needs to do).
Thanks,
Maddy

**Comment by novitch** [comment]
Hi Adrien,
In order to show you that it can be interesting, I was looking for the same option. No problem to mix pathway for draft and genomeID.

Thanks for your tools,
Cheers, 
Alban.

**Comment by HadrienG** [comment]
Thanks for the feedback folks. I'll look into if for the next minor release.

**Comment by apcamargo** [comment]
Given that the amount of fragmented genomes is increasing really fast due to the popularization of MAGs, I think this feature would be really useful!

Mixing genome IDs and paths seems to be a good solution. I don't see a problem with it.

**Comment by HadrienG** [comment]
Planning this for `1.5.0`, which should be out before the end of June :)

**Comment by novitch** [comment]
:), Thanks, will use it on my next benchmark !

**Comment by apcamargo** [comment]
That's great! Thanks @HadrienG!
