### ISSUE TITLE
Issues with --cpus option

### ISSUE THREAD

**Issue by mladen5000** [HadrienG/InSilicoSeq#94]
I noticed that there were multiple copies of reads with the same ID in my simulated fastq files. After playing around with the parameters I noticed that the number of duplicates is directly proportional to the number of cpus I specify. For example, if I listed --cpus 4, I would have 4 reads with the name NC_021042.1_3/1. 

Each read is still unique except for the identifier, and the number of reads is still correct (~1mil by default)

**Comment by HadrienG** [comment]
Hi!

Thanks for reporting this. I'll take a look.

**Comment by HadrienG** [comment]
Solved in `1.3.5`!
