### ISSUE TITLE
Simulating targeted amplicon sequencing

### ISSUE THREAD

**Issue by standage** [HadrienG/InSilicoSeq#95]
Greetings! I have a Fasta file containing a few dozen amplicon sequences, and I would like to use InSilicoSeq to simulate targeted sequencing of these amplicons. I had originally used `--mode kde --model MiSeq`, but this resulted in a read length error. I'm currently trying out other configuration options, but in the mean time do you have any recommendations for simulating amplicon sequencing?

**Comment by standage** [comment]
In particular, I don't see any way to adjust the lengths of the reads generated.

**Comment by HadrienG** [comment]
Hi!

InSilicoSeq is aimed at simulating reads from whole metagenomes. For amplicons you could try [biogrinder](https://github.com/zyxue/biogrinder)

**Comment by HadrienG** [comment]
implemented in 2.0.0
